# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4485e6f59fbf769901c8ee4dffd6debcd3dd9336c3aea8ef42287ef25b13e9884f85777fee32a1170f4740d12727856a459ef03e1ab98e56299195191f0b9a50

test:
  secret_key_base: 037347c2ce67d035021ab6c8d5e2bdf25676605fec8cac19a3d07b5d62c0cf74cd4e59de87b937c759103f1c5460d9b5bb94058e483bd7c748672ded604fa268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
